FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY AuthPlatform.sln .

COPY AuthPlatform.Domain/AuthPlatform.Domain.csproj AuthPlatform.Domain/
COPY AuthPlatform.Application/AuthPlatform.Application.csproj AuthPlatform.Application/
COPY AuthPlatform.Infrastructure/AuthPlatform.Infrastructure.csproj AuthPlatform.Infrastructure/
COPY AuthPlatform.Api/AuthPlatform.Api.csproj AuthPlatform.Api/
COPY AuthPlatform.Mvc/AuthPlatform.Mvc.csproj AuthPlatform.Mvc/

RUN dotnet restore AuthPlatform.Mvc/AuthPlatform.Mvc.csproj

COPY . .

RUN dotnet publish AuthPlatform.Mvc/AuthPlatform.Mvc.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime

RUN apt-get update && apt-get install -y \
    libgdiplus \
    libc6-dev \
    libx11-dev \
    fontconfig \
    fonts-dejavu-core \
    libfreetype6 \
    libfontconfig1 \
    libxrender1 \
    libxext6 \
    && GDIPLUS_PATH=$(find /usr/lib -name "libgdiplus.so*" | head -n 1) \
    && ln -sf "$GDIPLUS_PATH" /usr/lib/gdiplus.dll \
    && ln -sf "$GDIPLUS_PATH" /usr/lib/gdiplus.dll.so \
    && ln -sf "$GDIPLUS_PATH" /usr/lib/libgdiplus.dll.so \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_HTTP_PORTS=8080
ENV ASPNETCORE_ENVIRONMENT=Production

EXPOSE 8080

ENTRYPOINT ["dotnet", "AuthPlatform.Mvc.dll"]