// <auto-generated />
using System;
using AuthPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521213904_AddLineTotalToInvoiceDetail")]
    partial class AddLineTotalToInvoiceDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthAuditActivity", b =>
                {
                    b.Property<int>("AuthAuditActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthAuditActivityId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("PerformedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthAuditActivityId");

                    b.ToTable("AuthAuditActivities", (string)null);
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthLoginHistory", b =>
                {
                    b.Property<int>("AuthLoginHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthLoginHistoryId"));

                    b.Property<int?>("AuthUserId")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthLoginHistoryId");

                    b.ToTable("AuthLoginHistories", (string)null);
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthPermission", b =>
                {
                    b.Property<int>("AuthPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthPermissionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthPermissionId");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("AuthPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            AuthPermissionId = 1,
                            Description = "Allows user to view expenditure heads",
                            IsActive = true,
                            PermissionCode = "ExpenditureHead.View",
                            PermissionName = "View Expenditure Heads"
                        },
                        new
                        {
                            AuthPermissionId = 2,
                            Description = "Allows user to create expenditure heads",
                            IsActive = true,
                            PermissionCode = "ExpenditureHead.Create",
                            PermissionName = "Create Expenditure Heads"
                        },
                        new
                        {
                            AuthPermissionId = 3,
                            Description = "Allows user to edit expenditure heads",
                            IsActive = true,
                            PermissionCode = "ExpenditureHead.Edit",
                            PermissionName = "Edit Expenditure Heads"
                        },
                        new
                        {
                            AuthPermissionId = 4,
                            Description = "Allows user to delete expenditure heads",
                            IsActive = true,
                            PermissionCode = "ExpenditureHead.Delete",
                            PermissionName = "Delete Expenditure Heads"
                        });
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthRefreshToken", b =>
                {
                    b.Property<int>("AuthRefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthRefreshTokenId"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthRefreshTokenId");

                    b.HasIndex("AuthUserId");

                    b.ToTable("AuthRefreshTokens", (string)null);
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthGroup", b =>
                {
                    b.Property<int>("AuthGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthGroupId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("AuthGroupId");

                    b.ToTable("AuthGroups", (string)null);

                    b.HasData(
                        new
                        {
                            AuthGroupId = 1,
                            Description = "System administrator",
                            IsActive = true,
                            GroupName = "Admin"
                        },
                        new
                        {
                            AuthGroupId = 2,
                            Description = "Read-only user",
                            IsActive = true,
                            GroupName = "Viewer"
                        });
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthGroupPermission", b =>
                {
                    b.Property<int>("AuthGroupPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthGroupPermissionId"));

                    b.Property<int>("AuthPermissionId")
                        .HasColumnType("int");

                    b.Property<int>("AuthGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthGroupPermissionId");

                    b.HasIndex("AuthPermissionId");

                    b.HasIndex("AuthGroupId");

                    b.ToTable("AuthGroupPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            AuthGroupPermissionId = 1,
                            AuthPermissionId = 1,
                            AuthGroupId = 1,
                            IsActive = true
                        },
                        new
                        {
                            AuthGroupPermissionId = 2,
                            AuthPermissionId = 2,
                            AuthGroupId = 1,
                            IsActive = true
                        },
                        new
                        {
                            AuthGroupPermissionId = 3,
                            AuthPermissionId = 3,
                            AuthGroupId = 1,
                            IsActive = true
                        },
                        new
                        {
                            AuthGroupPermissionId = 4,
                            AuthPermissionId = 4,
                            AuthGroupId = 1,
                            IsActive = true
                        },
                        new
                        {
                            AuthGroupPermissionId = 5,
                            AuthPermissionId = 1,
                            AuthGroupId = 2,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthUser", b =>
                {
                    b.Property<int>("AuthUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthUserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AuthUsers", (string)null);

                    b.HasData(
                        new
                        {
                            AuthUserId = 1,
                            Email = "admin@authplatform.com",
                            FailedLoginAttempts = 0,
                            FirstName = "System",
                            IsActive = true,
                            IsLocked = false,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$PSakMju1u1ZzRcUAMf5N/eFytXLA8thb3FrKWDIw3SRnbIM.xeepa",
                            UserName = "admin"
                        },
                        new
                        {
                            AuthUserId = 2,
                            Email = "viewer@authplatform.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Normal",
                            IsActive = true,
                            IsLocked = false,
                            LastName = "Viewer",
                            PasswordHash = "$2a$11$PSakMju1u1ZzRcUAMf5N/eFytXLA8thb3FrKWDIw3SRnbIM.xeepa",
                            UserName = "viewer"
                        });
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthUserPermission", b =>
                {
                    b.Property<int>("AuthUserPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthUserPermissionId"));

                    b.Property<int>("AuthPermissionId")
                        .HasColumnType("int");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthUserPermissionId");

                    b.HasIndex("AuthPermissionId");

                    b.HasIndex("AuthUserId");

                    b.ToTable("AuthUserPermissions", (string)null);

                    b.HasData(
                        new
                        {
                            AuthUserPermissionId = 1,
                            AuthPermissionId = 1,
                            AuthUserId = 1,
                            IsActive = true
                        },
                        new
                        {
                            AuthUserPermissionId = 2,
                            AuthPermissionId = 2,
                            AuthUserId = 1,
                            IsActive = true
                        },
                        new
                        {
                            AuthUserPermissionId = 3,
                            AuthPermissionId = 3,
                            AuthUserId = 1,
                            IsActive = true
                        },
                        new
                        {
                            AuthUserPermissionId = 4,
                            AuthPermissionId = 4,
                            AuthUserId = 1,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthUserGroup", b =>
                {
                    b.Property<int>("AuthUserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthUserGroupId"));

                    b.Property<int>("AuthGroupId")
                        .HasColumnType("int");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthUserGroupId");

                    b.HasIndex("AuthGroupId");

                    b.HasIndex("AuthUserId");

                    b.ToTable("AuthUserGroups", (string)null);

                    b.HasData(
                        new
                        {
                            AuthUserGroupId = 1,
                            AuthGroupId = 1,
                            AuthUserId = 1,
                            IsActive = true
                        },
                        new
                        {
                            AuthUserGroupId = 2,
                            AuthGroupId = 2,
                            AuthUserId = 2,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("AuthPlatform.Domain.Expenditures.Entities.ExpenditureHead", b =>
                {
                    b.Property<int>("ExpenditureHeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenditureHeadId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExpenditureHeadName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExpenditureHeadId");

                    b.ToTable("ExpenditureHeads", (string)null);
                });

            modelBuilder.Entity("AuthPlatform.Domain.Expenditures.Entities.ExpenditureInvoice", b =>
                {
                    b.Property<int>("ExpenditureInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenditureInvoiceId"));

                    b.Property<int>("ExpenditureHeadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExpenditureInvoiceId");

                    b.HasIndex("ExpenditureHeadId");

                    b.ToTable("ExpenditureInvoices", (string)null);
                });

            modelBuilder.Entity("AuthPlatform.Domain.Expenditures.Entities.ExpenditureInvoiceDetail", b =>
                {
                    b.Property<int>("ExpenditureInvoiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenditureInvoiceDetailId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpenditureInvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RecordCreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordUpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RecordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExpenditureInvoiceDetailId");

                    b.HasIndex("ExpenditureInvoiceId");

                    b.ToTable("ExpenditureInvoiceDetails", (string)null);
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthRefreshToken", b =>
                {
                    b.HasOne("AuthPlatform.Domain.Auth.Entities.AuthUser", "AuthUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthGroupPermission", b =>
                {
                    b.HasOne("AuthPlatform.Domain.Auth.Entities.AuthPermission", "AuthPermission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("AuthPermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuthPlatform.Domain.Auth.Entities.AuthGroup", "AuthGroup")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("AuthGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthPermission");

                    b.Navigation("AuthGroup");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthUserPermission", b =>
                {
                    b.HasOne("AuthPlatform.Domain.Auth.Entities.AuthPermission", "AuthPermission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("AuthPermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuthPlatform.Domain.Auth.Entities.AuthUser", "AuthUser")
                        .WithMany("UserPermissions")
                        .HasForeignKey("AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthPermission");

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthUserGroup", b =>
                {
                    b.HasOne("AuthPlatform.Domain.Auth.Entities.AuthGroup", "AuthGroup")
                        .WithMany("UserGroups")
                        .HasForeignKey("AuthGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuthPlatform.Domain.Auth.Entities.AuthUser", "AuthUser")
                        .WithMany("UserGroups")
                        .HasForeignKey("AuthUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthGroup");

                    b.Navigation("AuthUser");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Expenditures.Entities.ExpenditureInvoice", b =>
                {
                    b.HasOne("AuthPlatform.Domain.Expenditures.Entities.ExpenditureHead", "ExpenditureHead")
                        .WithMany("Invoices")
                        .HasForeignKey("ExpenditureHeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenditureHead");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Expenditures.Entities.ExpenditureInvoiceDetail", b =>
                {
                    b.HasOne("AuthPlatform.Domain.Expenditures.Entities.ExpenditureInvoice", "ExpenditureInvoice")
                        .WithMany("Details")
                        .HasForeignKey("ExpenditureInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenditureInvoice");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthPermission", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthGroup", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Auth.Entities.AuthUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Expenditures.Entities.ExpenditureHead", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("AuthPlatform.Domain.Expenditures.Entities.ExpenditureInvoice", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
